# Generated by Django 2.2.6 on 2019-10-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Praveen',
            fields=[
                ('user', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('mob', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
